---
- name: Deploy resources via Terraform
  hosts: localhost
  tasks:
    - name: Terraform apply
      cloud.terraform.terraform:
        project_path: terraform-project/
        state: present
        force_init: true
        backend_config_files:
          - "{{ lookup('env', 'TF_BACKEND_CONFIG_FILE') }}"
      register: result

    - name: Debug result
      ansible.builtin.debug:
        msg: "{{ result }}"
