---
- name: Destroy Terraform resources
  hosts: localhost

  tasks:
    - name: Terraform destroy
      cloud.terraform.terraform:
        project_path: terraform/
        state: absent
        backend_config_files:
          - "{{ lookup('env', 'TF_BACKEND_CONFIG_FILE') }}"
      register: result

    - name: Debug result
      ansible.builtin.debug:
        msg: "{{ result }}"
